[target.'cfg(target_os = "macos")']
rustflags = [
    "-A", "unexpected_cfgs",
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
    "-C", "link-arg=-Wl,-install_name,@rpath/libbtleplug_client.dylib"
]

[target.x86_64-unknown-linux-gnu]
rustflags = [ "-Clink-args=-Wl,-rpath,$ORIGIN" ]

[target.aarch64-unknown-linux-gnu]
rustflags = [ "-Clink-args=-Wl,-rpath,$ORIGIN" ]


# See https://github.com/rust-lang/rust/issues/59302
[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=-crt-static"
]

# Same as above
[target.aarch64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=-crt-static"
]

# Libatomic is needed for 32 bits ARM.
# See: https://github.com/philss/rustler_precompiled/issues/53
[target.arm-unknown-linux-gnueabihf]
rustflags = [
  "-l", "dylib=atomic"
]

[patch.crates-io]
# bluster = { path = "./patches/bluster.patch" }
#uuid = { git = "https://github.com/uuid-rs/uuid.git", branch = "main" }

# Provides a small build size, but takes more time to build.
[profile.release]
lto = true

[build]
rustflags = ["-A", "unexpected_cfgs"]