[target.'cfg(target_os = "macos")']
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [ "-Clink-args=-Wl,-rpath,$ORIGIN" ]

[target.aarch64-unknown-linux-gnu]
rustflags = [ "-Clink-args=-Wl,-rpath,$ORIGIN" ]

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-C target-feature=-crt-static", "-C link-arg=-static"]

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-C target-feature=-crt-static", "-C link-arg=-static"]