name: Rust CI
on:
  push:
    branches:
    - main
    - refactoring
    paths:
    - "native/**"
  pull_request:
    paths:
    - "native/**"
  workflow_dispatch:


jobs:
  lint-rust:
    name: Lint Rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest:
        - native/btleplug_client/Cargo.toml

    steps:
    - name: install ble packages
      run: sudo apt install libdbus-1-dev pkg-config

    - uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          native/btleplug_client
      #pkg-config libudev-dev libglib2.0-dev libusb-1.0-0-dev libboost-all-dev libevdev-dev

    - name: run rustfmt
      run: cargo fmt --manifest-path=${{ matrix.manifest }} --all -- --check

    - name: run clippy
      run: cargo clippy --manifest-path=${{ matrix.manifest }} -- -Dwarnings
